name: Build and Release V3XV0ID Image Animator

on:
  push:
    tags:
      - 'v*' # Triggers on version tags like v1.0.0, v1.1.0, etc.
  workflow_dispatch: # Allows manual triggering

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        include:
          - os: macos-latest
            platform: mac
            artifact_name: "V3XV0ID-Image-Animator-mac"
          - os: windows-latest
            platform: win
            artifact_name: "V3XV0ID-Image-Animator-win"
          - os: ubuntu-latest
            platform: linux
            artifact_name: "V3XV0ID-Image-Animator-linux"

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build for macOS
        if: matrix.platform == 'mac'
        run: npm run build-mac
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build for Windows
        if: matrix.platform == 'win'
        run: npm run build-win
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build for Linux
        if: matrix.platform == 'linux'
        run: npm run build-linux
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload macOS artifacts
        if: matrix.platform == 'mac'
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: |
            dist/*.dmg
            dist/*.zip
          retention-days: 30

      - name: Upload Windows artifacts
        if: matrix.platform == 'win'
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: |
            dist/*.exe
            dist/*.msi
            dist/*.zip
          retention-days: 30

      - name: Upload Linux artifacts
        if: matrix.platform == 'linux'
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: |
            dist/*.AppImage
            dist/*.deb
            dist/*.rpm
            dist/*.tar.gz
          retention-days: 30

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - name: Display structure of downloaded files
        run: ls -la ./artifacts

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: V3XV0ID Image Animator ${{ github.ref_name }}
          body: |
            # V3XV0ID Image Animator ${{ github.ref_name }}
            
            ## 🎭 Professional Live Visual Performance Tool
            
            A cutting-edge dual-palette crossfading image and video animator with V3XV0ID cyber aesthetic branding.
            
            ### ✨ Features:
            - 🎛️ **Dual Palette System** - Professional DJ/VJ-style crossfader interface
            - 🎬 **Live Video Support** - .mp4, .mov, .avi, .webm, .mkv files with real-time playback
            - 🖼️ **Image Animation** - Multi-layer image sequences with effects
            - 👁️ **Live Preview Windows** - Real-time preview of Palette A, B, and mixed output
            - 🎨 **Visual Effects** - Opacity, scale, jitter, strobe, impact, and inverse color effects
            - 🖱️ **Drag & Drop** - Intuitive layer positioning and reordering
            - ⚡ **Real-time Performance** - Optimized for live visual performances
            - 🎯 **Dual Monitor Support** - Separate control and output windows for professional setups
            
            ### 📦 Downloads:
            Choose the version for your platform:
            
            **macOS:**
            - Intel Macs: `V3XV0ID Image Animator-x.x.x.dmg`
            - Apple Silicon: `V3XV0ID Image Animator-x.x.x-arm64.dmg`
            - Portable: `.zip` files
            
            **Windows:**
            - Installer: `V3XV0ID Image Animator Setup x.x.x.exe`
            - Portable: `V3XV0ID Image Animator x.x.x.exe`
            
            **Linux:**
            - AppImage: `V3XV0ID Image Animator-x.x.x.AppImage`
            - Debian: `v3xv0id-image-animator_x.x.x_amd64.deb`
            
            ### 🚀 Quick Start:
            1. Launch the application
            2. Add layers to Palette A and B using the "+ ADD" buttons
            3. Load images/videos into layers using the 📁 button
            4. Use the crossfader to mix between palettes
            5. Adjust effects with the controls panel
            
            Perfect for VJs, live performers, and visual artists!
          draft: false
          prerelease: false

      - name: Upload macOS DMG (Intel)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./artifacts/V3XV0ID-Image-Animator-mac/V3XV0ID Image Animator-1.0.0.dmg
          asset_name: V3XV0ID-Image-Animator-${{ github.ref_name }}-intel.dmg
          asset_content_type: application/octet-stream

      - name: Upload macOS DMG (ARM64)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./artifacts/V3XV0ID-Image-Animator-mac/V3XV0ID Image Animator-1.0.0-arm64.dmg
          asset_name: V3XV0ID-Image-Animator-${{ github.ref_name }}-arm64.dmg
          asset_content_type: application/octet-stream

      - name: Upload macOS ZIP (Intel)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./artifacts/V3XV0ID-Image-Animator-mac/V3XV0ID Image Animator-1.0.0-mac.zip
          asset_name: V3XV0ID-Image-Animator-${{ github.ref_name }}-intel-portable.zip
          asset_content_type: application/zip

      - name: Upload macOS ZIP (ARM64)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./artifacts/V3XV0ID-Image-Animator-mac/V3XV0ID Image Animator-1.0.0-arm64-mac.zip
          asset_name: V3XV0ID-Image-Animator-${{ github.ref_name }}-arm64-portable.zip
          asset_content_type: application/zip

      # Windows uploads will be added when the artifacts are available
      # Linux uploads will be added when the artifacts are available 