name: Build Test

on:
  push:
    branches: [ main, develop, simplify ]
  pull_request:
    branches: [ main, develop, simplify ]
  workflow_dispatch:

jobs:
  build-test:
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Test build for macOS
        if: runner.os == 'macOS'
        run: npm run build-mac

      - name: Test build for Windows
        if: runner.os == 'Windows'
        run: npm run build-win

      - name: Test build for Linux
        if: runner.os == 'Linux'
        run: npm run build-linux

      - name: List build output
        run: ls -la dist/ || dir dist\ 